# Site settings
title: My Code Path
header-img: img/home-bg.jpg
email: itshilei@gmail.com
description: "Talk is cheap, show me your code!"
baseurl: "/blog"
twitter_username: itshilei
github_username:  shic
facebook_username:  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 50
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# default settings
defaults:
  # default for post
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      layout: "post"
      author: Shi
      comments: true

  # default for pages
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "page"
    values:
      layout: "page"
      author: Shi
